/* Autogenerated lightweight stubs used only for static analysis include scans.
 * Real builds include zsh.mdh/config.h through zpmod.mdh. */
#pragma once
#ifndef UNUSED
#define UNUSED(x) x
#endif
typedef void *Module;
/* Provide minimal declarations to avoid parser errors when analyzers scan
 * files out-of-context. */
int bin_custom_dot(char *UNUSED(name), char **UNUSED(argv), UNUSED(void *ops),
                   UNUSED(int func));
int setup_(UNUSED(Module m));
int enables_(UNUSED(Module m), int **UNUSED(enables));
int boot_(UNUSED(Module m));
int cleanup_(UNUSED(Module m));
int finish_(UNUSED(Module m));
