---
name: 🐧 Build (Linux)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          scandir: "./Scripts/install.sh"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: ⚙️ Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      - name: ⚙️ Build
        run: sh ./Scripts/install.sh && ls -a $HOME/.zi/zmodules/zpmod/Src/zi
      - name: ⚙️ Load
        run: |
          module_path+=( "$HOME/.zi/zmodules/zpmod/Src" )
          zmodload zi/zpmod
          zpmod source-study -l
        shell: zsh {0}
