---
name: 🐧 Build (Linux)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read    
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          scandir: "./Scripts/install.sh"

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: 📦 Cache Zsh
        uses: actions/cache@v4
        with:
          path: ~/.cache/zsh
          key: ${{ runner.os }}-zsh-${{ hashFiles('**/Scripts/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-zsh-

      - name: ⚙️ Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: ⚙️ Build and List Files
        run: sh ./Scripts/install.sh && ls -a $HOME/.zi/zmodules/zpmod/Src/zi

      - name: ⚙️ Load Module
        run: |
          module_path+=( "$HOME/.zi/zmodules/zpmod/Src" )
          zmodload zi/zpmod
          zpmod source-study -l
        shell: zsh {0}
